version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/pileup_buster}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - QRZ_USERNAME=${QRZ_USERNAME}
      - QRZ_PASSWORD=${QRZ_PASSWORD}
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env:ro
    depends_on:
      - mongo
    command: poetry run uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    command: npm start

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=pileup_buster

volumes:
  mongo_data: