services:
  # MongoDB database
  mongodb:
    image: mongo:7
    container_name: pileup-buster-mongo
    environment:
      MONGO_INITDB_DATABASE: pileup_buster
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - pileup-network

  # Backend API service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: pileup-buster-backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/pileup_buster
      - SECRET_KEY=your-secret-key-change-in-production
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - pileup-network
    volumes:
      # For development: mount source code
      - ./backend:/app
    command: ["python", "app.py"]

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pileup-buster-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - pileup-network

volumes:
  mongodb_data:

networks:
  pileup-network:
    driver: bridge